import { ClickHouseClient } from '@clickhouse/client';

export async function seed(client: ClickHouseClient, database: string): Promise<void> {
  console.log('📊 Seeding sample audit logs...');

  const sampleLogs = [
    {
      user_id: 'user-123',
      user_email: 'superadmin.telemetryflow@telemetryflow.id',
      user_first_name: 'Super',
      user_last_name: 'Administrator',
      event_type: 'AUTH',
      action: 'login',
      resource: 'auth',
      result: 'SUCCESS',
      error_message: '',
      ip_address: '192.168.1.100',
      user_agent: 'Mozilla/5.0',
      metadata: '{"method":"password"}',
      tenant_id: 'tenant-1',
      workspace_id: 'workspace-1',
      organization_id: 'org-1',
      session_id: 'session-1',
      duration_ms: 150,
      hours_ago: 1,
    },
    {
      user_id: 'user-456',
      user_email: 'developer.telemetryflow@telemetryflow.id',
      user_first_name: 'Developer',
      user_last_name: 'TelemetryFlow',
      event_type: 'AUTH',
      action: 'login',
      resource: 'auth',
      result: 'SUCCESS',
      error_message: '',
      ip_address: '192.168.1.101',
      user_agent: 'Mozilla/5.0',
      metadata: '{"method":"password"}',
      tenant_id: 'tenant-1',
      workspace_id: 'workspace-1',
      organization_id: 'org-1',
      session_id: 'session-2',
      duration_ms: 120,
      hours_ago: 2,
    },
    {
      user_id: 'user-123',
      user_email: 'superadmin.telemetryflow@telemetryflow.id',
      user_first_name: 'Super',
      user_last_name: 'Administrator',
      event_type: 'DATA',
      action: 'create',
      resource: 'users',
      result: 'SUCCESS',
      error_message: '',
      ip_address: '192.168.1.100',
      user_agent: 'Mozilla/5.0',
      metadata: '{"userId":"new-user-1","email":"newuser@example.com"}',
      tenant_id: 'tenant-1',
      workspace_id: 'workspace-1',
      organization_id: 'org-1',
      session_id: 'session-1',
      duration_ms: 250,
      minutes_ago: 30,
    },
    {
      user_id: 'unknown',
      user_email: 'hacker@example.com',
      user_first_name: '',
      user_last_name: '',
      event_type: 'AUTH',
      action: 'login',
      resource: 'auth',
      result: 'FAILURE',
      error_message: 'Invalid credentials',
      ip_address: '203.0.113.1',
      user_agent: 'curl/7.68.0',
      metadata: '{"attempts":3}',
      tenant_id: '',
      workspace_id: '',
      organization_id: '',
      session_id: 'session-fail-1',
      duration_ms: 50,
      hours_ago: 3,
    },
    {
      user_id: 'user-456',
      user_email: 'developer.telemetryflow@telemetryflow.id',
      user_first_name: 'Developer',
      user_last_name: 'TelemetryFlow',
      event_type: 'AUTHZ',
      action: 'delete',
      resource: 'users',
      result: 'DENIED',
      error_message: 'Insufficient permissions',
      ip_address: '192.168.1.101',
      user_agent: 'Mozilla/5.0',
      metadata: '{"required":"users:delete"}',
      tenant_id: 'tenant-1',
      workspace_id: 'workspace-1',
      organization_id: 'org-1',
      session_id: 'session-2',
      duration_ms: 10,
      minutes_ago: 20,
    },
  ];

  for (const log of sampleLogs) {
    const now = new Date();
    const timestamp = log.hours_ago
      ? new Date(now.getTime() - log.hours_ago * 60 * 60 * 1000)
      : new Date(now.getTime() - (log.minutes_ago || 0) * 60 * 1000);

    await client.insert({
      table: `${database}.audit_logs`,
      values: [
        {
          timestamp: timestamp.toISOString().replace('T', ' ').replace('Z', ''),
          user_id: log.user_id,
          user_email: log.user_email,
          user_first_name: log.user_first_name,
          user_last_name: log.user_last_name,
          event_type: log.event_type,
          action: log.action,
          resource: log.resource,
          result: log.result,
          error_message: log.error_message,
          ip_address: log.ip_address,
          user_agent: log.user_agent,
          metadata: log.metadata,
          tenant_id: log.tenant_id,
          workspace_id: log.workspace_id,
          organization_id: log.organization_id,
          session_id: log.session_id,
          duration_ms: log.duration_ms,
        },
      ],
      format: 'JSONEachRow',
    });
  }

  console.log(`   ✅ Seeded ${sampleLogs.length} sample audit logs`);
}
